apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: maccpr7/backend-java:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    service: backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app: backend
